//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 28.09.2017 13:24:32
namespace MissionsConsoleClient.MissionsService.Models
{
    /// <summary>
    /// There are no comments for MissionSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MissionSingle")]
    public partial class MissionSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Mission>
    {
        /// <summary>
        /// Initialize a new MissionSingle object.
        /// </summary>
        public MissionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new MissionSingle object.
        /// </summary>
        public MissionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new MissionSingle object.
        /// </summary>
        public MissionSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Mission> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Mission in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Mission")]
    public partial class Mission : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Mission object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="taskState">Initial value of TaskState.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Mission CreateMission(int ID, string name, global::MissionsConsoleClient.MissionsService.Models.State taskState)
        {
            Mission mission = new Mission();
            mission.Id = ID;
            mission.Name = name;
            mission.TaskState = taskState;
            return mission;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Deadline in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Deadline")]
        public global::System.Nullable<global::System.DateTimeOffset> Deadline
        {
            get
            {
                return this._Deadline;
            }
            set
            {
                this.OnDeadlineChanging(value);
                this._Deadline = value;
                this.OnDeadlineChanged();
                this.OnPropertyChanged("Deadline");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Deadline;
        partial void OnDeadlineChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDeadlineChanged();
        /// <summary>
        /// There are no comments for Property DateOfCompletion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DateOfCompletion")]
        public global::System.Nullable<global::System.DateTimeOffset> DateOfCompletion
        {
            get
            {
                return this._DateOfCompletion;
            }
            set
            {
                this.OnDateOfCompletionChanging(value);
                this._DateOfCompletion = value;
                this.OnDateOfCompletionChanged();
                this.OnPropertyChanged("DateOfCompletion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateOfCompletion;
        partial void OnDateOfCompletionChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateOfCompletionChanged();
        /// <summary>
        /// There are no comments for Property TaskState in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TaskState")]
        public global::MissionsConsoleClient.MissionsService.Models.State TaskState
        {
            get
            {
                return this._TaskState;
            }
            set
            {
                this.OnTaskStateChanging(value);
                this._TaskState = value;
                this.OnTaskStateChanged();
                this.OnPropertyChanged("TaskState");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::MissionsConsoleClient.MissionsService.Models.State _TaskState;
        partial void OnTaskStateChanging(global::MissionsConsoleClient.MissionsService.Models.State value);
        partial void OnTaskStateChanged();
        /// <summary>
        /// There are no comments for Property IsDeferFromInitial in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("isDeferFromInitial")]
        public global::System.Nullable<bool> IsDeferFromInitial
        {
            get
            {
                return this._IsDeferFromInitial;
            }
            set
            {
                this.OnIsDeferFromInitialChanging(value);
                this._IsDeferFromInitial = value;
                this.OnIsDeferFromInitialChanged();
                this.OnPropertyChanged("isDeferFromInitial");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<bool> _IsDeferFromInitial;
        partial void OnIsDeferFromInitialChanging(global::System.Nullable<bool> value);
        partial void OnIsDeferFromInitialChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for State in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("State")]
    public enum State : byte
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Waiting")]
        Waiting = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Changed")]
        Changed = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Canceled")]
        Canceled = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Finished")]
        Finished = 3
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::MissionsConsoleClient.MissionsService.Models.Mission as global::MissionsConsoleClient.MissionsService.Models.MissionSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::MissionsConsoleClient.MissionsService.Models.MissionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::MissionsConsoleClient.MissionsService.Models.Mission> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::MissionsConsoleClient.MissionsService.Models.MissionSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::MissionsConsoleClient.MissionsService.Models.Mission as global::MissionsConsoleClient.MissionsService.Models.MissionSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::MissionsConsoleClient.MissionsService.Models.MissionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::MissionsConsoleClient.MissionsService.Models.Mission> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::MissionsConsoleClient.MissionsService.Models.MissionSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace MissionsConsoleClient.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "MissionsService.Models", "MissionsConsoleClient.MissionsService.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "MissionsConsoleClient.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("MissionsConsoleClient.MissionsService.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("MissionsService.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("MissionsService.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("MissionsConsoleClient.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Missions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Missions")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::MissionsConsoleClient.MissionsService.Models.Mission> Missions
        {
            get
            {
                if ((this._Missions == null))
                {
                    this._Missions = base.CreateQuery<global::MissionsConsoleClient.MissionsService.Models.Mission>("Missions");
                }
                return this._Missions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::MissionsConsoleClient.MissionsService.Models.Mission> _Missions;
        /// <summary>
        /// There are no comments for Missions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToMissions(global::MissionsConsoleClient.MissionsService.Models.Mission mission)
        {
            base.AddObject("Missions", mission);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""MissionsService.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Mission"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""Description"" Type=""Edm.String"" />
        <Property Name=""Deadline"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""DateOfCompletion"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""TaskState"" Type=""MissionsService.Models.State"" Nullable=""false"" />
        <Property Name=""isDeferFromInitial"" Type=""Edm.Boolean"" />
      </EntityType>
      <EnumType Name=""State"" UnderlyingType=""Edm.Byte"">
        <Member Name=""Waiting"" Value=""0"" />
        <Member Name=""Changed"" Value=""1"" />
        <Member Name=""Canceled"" Value=""2"" />
        <Member Name=""Finished"" Value=""3"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Missions"" EntityType=""MissionsService.Models.Mission"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
